/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_me_eldog_fface_FaceCaptureView */

#ifndef _Included_uk_me_eldog_fface_FaceCaptureView
#define _Included_uk_me_eldog_fface_FaceCaptureView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_me_eldog_fface_FaceCaptureView
 * Method:    loadFaceDetector
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_uk_me_eldog_fface_FaceCaptureView_loadFaceDetector
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     uk_me_eldog_fface_FaceCaptureView
 * Method:    findFaces
 * Signature: (JII[B[I)J
 */
JNIEXPORT jlong JNICALL Java_uk_me_eldog_fface_FaceCaptureView_findFaces
  (JNIEnv *, jclass, jlong, jint, jint, jbyteArray, jintArray);

/*
 * Class:     uk_me_eldog_fface_FaceCaptureView
 * Method:    releaseFaceDetector
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_uk_me_eldog_fface_FaceCaptureView_releaseFaceDetector
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
