/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_me_eldog_fface_FaceCaptureActivity */

#ifndef _Included_uk_me_eldog_fface_FaceCaptureActivity
#define _Included_uk_me_eldog_fface_FaceCaptureActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef uk_me_eldog_fface_FaceCaptureActivity_DIALOG_ENSURE_DATA_FILES_EXIST_ID
#define uk_me_eldog_fface_FaceCaptureActivity_DIALOG_ENSURE_DATA_FILES_EXIST_ID 0L
#undef uk_me_eldog_fface_FaceCaptureActivity_DIALOG_LOAD_FACE_DETECTOR_ID
#define uk_me_eldog_fface_FaceCaptureActivity_DIALOG_LOAD_FACE_DETECTOR_ID 1L
#undef uk_me_eldog_fface_FaceCaptureActivity_DIALOG_FINDING_FACES_ID
#define uk_me_eldog_fface_FaceCaptureActivity_DIALOG_FINDING_FACES_ID 2L
#undef uk_me_eldog_fface_FaceCaptureActivity_DIALOG_ANALYSING_ATTRACTIVENESS_ID
#define uk_me_eldog_fface_FaceCaptureActivity_DIALOG_ANALYSING_ATTRACTIVENESS_ID 3L
#undef uk_me_eldog_fface_FaceCaptureActivity_MAX_FACES
#define uk_me_eldog_fface_FaceCaptureActivity_MAX_FACES 5L
#undef uk_me_eldog_fface_FaceCaptureActivity_INTENT_PICTURE_TAKEN
#define uk_me_eldog_fface_FaceCaptureActivity_INTENT_PICTURE_TAKEN 0L
/*
 * Class:     uk_me_eldog_fface_FaceCaptureActivity
 * Method:    runConv
 * Signature: (Ljava/lang/String;[I)D
 */
JNIEXPORT jdouble JNICALL Java_uk_me_eldog_fface_FaceCaptureActivity_runConv
  (JNIEnv *, jclass, jstring, jintArray);

#ifdef __cplusplus
}
#endif
#endif
