/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_me_eldog_fface_FaceCaptureActivity_EnsureExternalDirectory */

#ifndef _Included_uk_me_eldog_fface_FaceCaptureActivity_EnsureExternalDirectory
#define _Included_uk_me_eldog_fface_FaceCaptureActivity_EnsureExternalDirectory
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
