/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_me_eldog_fface_ViewScoreActivity */

#ifndef _Included_uk_me_eldog_fface_ViewScoreActivity
#define _Included_uk_me_eldog_fface_ViewScoreActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef uk_me_eldog_fface_ViewScoreActivity_DIALOG_ANALYSING_ATTRACTIVENESS_ID
#define uk_me_eldog_fface_ViewScoreActivity_DIALOG_ANALYSING_ATTRACTIVENESS_ID 0L
#undef uk_me_eldog_fface_ViewScoreActivity_DIALOG_LOAD_FACE_DETECTOR_ID
#define uk_me_eldog_fface_ViewScoreActivity_DIALOG_LOAD_FACE_DETECTOR_ID 1L
/*
 * Class:     uk_me_eldog_fface_ViewScoreActivity
 * Method:    runConv
 * Signature: (Ljava/lang/String;[I)D
 */
JNIEXPORT jdouble JNICALL Java_uk_me_eldog_fface_ViewScoreActivity_runConv
  (JNIEnv *, jclass, jstring, jintArray);

#ifdef __cplusplus
}
#endif
#endif
