/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ConvNet */

#ifndef _Included_ConvNet
#define _Included_ConvNet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ConvNet
 * Method:    runConv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_ConvNet_runConv
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
